// <auto-generated />
using Bookstore.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Bookstore.Web.Migrations
{
    [DbContext(typeof(BookstoreDbContext))]
    [Migration("20210614194527_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Bookstore.Web.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorName = "Bilal ÖZTÜRK",
                            Description = "My Last Book In Programming Languages.",
                            ImagePath = "team-image-2-646x680.jpg",
                            Publisher = "Time Magazine",
                            Title = "Dart Programming Tutorial For Beginners"
                        },
                        new
                        {
                            Id = 2,
                            AuthorName = "Mustafa Kaslı",
                            Description = "My Third Book In Programming Languages.",
                            ImagePath = "about-1-570x350.jpg",
                            Publisher = "The Cut",
                            Title = "Paython Programming Tutorial For Beginners"
                        },
                        new
                        {
                            Id = 3,
                            AuthorName = "Ahmet Demir",
                            Description = "My Second Book In Programming Languages.",
                            ImagePath = "team-image-1-646x680.jpg",
                            Publisher = "The Next Web",
                            Title = "C# Programming Tutorial For Beginners"
                        },
                        new
                        {
                            Id = 4,
                            AuthorName = "Leyla ÖZTÜRK",
                            Description = "My First Book In Programming Languages.",
                            ImagePath = "team-image-3-646x680.jpg",
                            Publisher = "BBC TV",
                            Title = "Java Programming Tutorial For Beginners"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
